### ISSUE TITLE
Local changes in /config/scripts are overwritten

### ISSUE THREAD

**Issue by Cheezzhead** [RandomNinjaAtk/docker-amtd#21]
When it comes to the script locations, the current behavior is that, on startup:

- the contents of `/config/scripts` is removed;
- the contents of `/scripts` is copied to `/config/scripts`;
- the scripts in `/config/scripts` are used by the container.

This seems backward to me. `/config/scripts` is the folder that will (most likely) be available on a user's host machine, and thus will be the one where local changes are made. The way the container is currently setup will overwrite those changes with the default scripts from `/scripts`.

Instead, if on startup:

- the contents of `/scripts` is removed;
- the contents of `/config/scripts` is copied to `scripts`;
- the scripts in `/scripts` are used by the container (optional).
- or alternatively, just use a softlink from `/config/scripts` to `/scripts`

Then local changes can be made within the `/config` folder (as intended) on the host machine.

**Comment by RandomNinjaAtk** [comment]
Changes can be made normally to the regular /config folder. Just not /config/scripts because they get overwritten on restarts. The reason for overwrites is to make sure the scripts are always updated and using the latest code provided by the image. For dev testing, I typically disable auto-start and make a copy of the main script and store it in /config and execute manually...

I don't necessarily see a better way of doing it because the intention is always to use the latest code from the docker, and the current setup provides that.

So I'm not sure I see any issue, because all local changes work, just not in the /config/scripts folder, and that is by design...

**Comment by Cheezzhead** [comment]
Ah, I see. I've always used docker with the philosophy in mind that local changes should stack on top of the images. Which is why I was confused that the scripts from the images were overwriting my own scripts. 

I understand the idea behind wanting to use the latest code from the image, and the current solution is adequate for dev testing. But when it comes to a production environment, if someone wanted to make a specific change to any of the scripts, it would be overwritten on the next restart.

As for using the latest code, overwriting image files with local changes carries the implicit risk of not keeping up-to-date with newer image tags.
