### ISSUE TITLE
[REQ] - Check for existing trailers

### ISSUE THREAD

**Issue by trickiegt** [RandomNinjaAtk/docker-amtd#25]
Can you add support to check for existing trailers located in the movie folder?

Flow:
Scan media
  - No IMDB#-complete file found
  - check movie folder for *trailer*
    - if found, create IMDB#-complete file
    - else scan for trailer to download

I tried modifying the download.bash file but apparently you have it setup to replace the file with default every time the docker container is loaded.

Anyways, what I have done for now is create the ###-complete file manually
Not a big deal, just a thought.

Thanks for the consideration and all the hard work and effort you put into making this
Chris

**Comment by RandomNinjaAtk** [comment]
So after reviewing, it does check in multiple places... So I'm not sure why your asking for it? If you had your own trailers not using the script, that would be why it didn't find them. Because the script checks for files based on it's own output... So if your previous files were not named exactly as the script expected, it wouldn't detect them and it would initiate new downloads...

You can see where it checks in a few places:
https://github.com/RandomNinjaAtk/docker-amtd/blob/40a832d58d4081de00498a1dda58cae0f8e85515/root/scripts/download.bash#L174-L177
https://github.com/RandomNinjaAtk/docker-amtd/blob/40a832d58d4081de00498a1dda58cae0f8e85515/root/scripts/download.bash#L298-L301

**Comment by trickiegt** [comment]
I agree with you on all counts.  I examined both of those lines of code and came to the same conclusion -- If the file did not have the filename amtd was looking for it would assume it did not exist.

Here's a quick rundown of what happened for me and what brought me to wanting to include a `find . -name '*-trailer.*'`
I had 0 trailers, discovered your script, setup & ran amtd.  It found just about everything with the exception of 8-10 files.
The trailers it did not find or could not download for X reason, I looked up manually, downloaded, saved as -trailer.mp4 in each movie folder.
Ran the script again thinking it would discover that the trailer was already present and it did not
Reviewed your code and manually created the -complete file so it wouldn't continue to look for those movies

This is just a thought/recommendation if you are open to the idea
The first check is for a local file -complete
The 2nd check goes online and searches for a trailer -- once found it checks to see if that file already exists
--I'm thinking it may be wise to make the 2nd check also a local check to reduce web polling
--I was going to try using the command  `find . -name '*-trailer.*'` to accomplish this however was unsuccessful in attempting as the scripts get re-written on docker restart

Again I greatly appreciate the time and effort you put into making amtd a reality for everyone.  I'm a bit of a linux newbie with rudimentary programming knowledge/experience and could have never made something like this myself. That being said, I hope you do not take offense and also it may be a poor idea -- I don't know enough =)

Many Thanks,
Chris

**Comment by trickiegt** [comment]
Okay, so I was able to modify and test the code.  Noticed today your comment on manually running the script
`bash /config/scripts/download.bash`

The modifications work well -- it will check for a file *-trailer* in the movie folder.  If it finds one, it will create the -complete file and move on to the next movie.

Here's what I added to your download.bash file
`radarrmoviepath="$(echo "${radarrmoviedata}" | jq -r ".path")"`
`if [ -f "/config/cache/${themoviedbmovieid}-complete" ]; then`
`	echo "$currentprocessid of $radarrmovietotal :: $radarrmovietitle :: All videos already downloaded, skipping..."`
`	continue`
`else`
`	localtrailer=$(find "$radarrmoviepath" -name *-trailer.* | wc -l)`
`	if [ $localtrailer -eq 0 ]; then`
`		echo "No Local Trailers Found With name *-trailer* -- searching online"`
`	else`
`		echo "$currentprocessid of $radarrmovietotal :: $radarrmovietitle :: Found a local file matching *-trailer*!"`
`		touch "/config/cache/${themoviedbmovieid}-complete"`
`		continue`
`	fi`
`fi`
moved radarrmoviepath to the top so it would be declared, it was originally under the if statement

**Comment by SomeRandomUserIsHere** [comment]
Was this ever implemented? I ask because this is also critical to me and is preventing me from trying out your Docker, which looks awesome btw so thank you. My use case is that I already have thousands of trailers downloaded alongside my media files, most named "movie-trailer.ext" and some as "moviename (year)-trailer.ext" -- both get picked up by Plex no problem. I wouldn't want this script to download thousands of trailers that already exist, or worse, replace the ones I already have meticulously sourced over the years. The above solution by tickiegt is perfect, and I would think make this script much safer for new users to implement, and just an improved approach overall. Thanks for your consideration!

**Comment by RandomNinjaAtk** [comment]
See if the latest update solves it for you... There is a new setting to control it... @SomeRandomUserIsHere & @trickiegt
