### ISSUE TITLE
auto run

### ISSUE THREAD

**Issue by foXaCe** [RandomNinjaAtk/docker-amtd#5]
hello , this script is great.

how to auto-excute after movie is downloaded ?

**Comment by RandomNinjaAtk** [comment]
This script does not have that feature, if you have auto start enabled it will detect missing trailers on every run and download them accordingly. I wouldn't know where to begin to integrate it that way. Other than a custom Radarr container with the script. Which I have done in the past but prefer this method.

**Comment by foXaCe** [comment]
ok thanks you

**Comment by foXaCe** [comment]
maybe a sh file like this one might work

https://github.com/mdhiggins/sonarr-sma/issues/6

**Comment by RandomNinjaAtk** [comment]
Thanks for the thought, but that only works because its all packaged in the same container. This script would need its own api of sorts to execute it remotely, and that is beyond me at the moment. 

I have my own versions of radarr/sonarr with extra tools added where it could also be implemented, but for now I thought it would be easier to maintain to have it more isolated. 

There is a version of this request actually already packaged in my own container, I just don't really disclose it...
https://github.com/RandomNinjaAtk/docker-radarr-sma/blob/master/root/scripts/DownloadTrailer.bash

**Comment by foXaCe** [comment]
ok thanks you

**Comment by austinwbest** [comment]
Use a Custom Script in *arr that calls your script (trigger it for download event). It has all the variables needed to query the *arr api for the trailer info or query tmdb|tvdb for video information.

**Comment by foXaCe** [comment]
How to ?

**Comment by RandomNinjaAtk** [comment]
@austinwbest I think that would only be possible if Radarr was not running as a container, I'm not aware of any way to directly send commands between containers, from another container, unless you setup some sort of SSH scenario.

If there is a way to do what your saying, I'd be curious to know more. You can find me on the discord channels for radarr (I have a donator status)

**Comment by austinwbest** [comment]
Yes, i know who you are. I am nitsua on discord :) 

Ideally you need to make this script standalone so it can be added with a simple custom script call. It can include all needed packages and then everything stays in the *arr container.

**Comment by RandomNinjaAtk** [comment]
@austinwbest Yeah, I have a custom container that I've done that with. I just like separation to hopefully make things simpler to maintain. My custom container already has the capability, its just not advertised...

Also adding all the packages into the script is not great, because that would require a reinstall of the packages on every upgrade and thats not really ideal. Trying to keep things simple... but always open to ideas for improvements.

**Comment by RandomNinjaAtk** [comment]
Closing this because no changes are needed at this time...
